# Generated by Django 3.1.14 on 2022-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
